#! /bin/bash

prompts=(
"Write a news report for a fictional city of your choice. Do not include a title or any other formatting."
"Write an eyewitness account of a minor historical event that never actually happened."
"Describe a city council meeting where everyone agrees but for completely different reasons."
"Write a classified memo that was accidentally leaked to the public."
"Write a weather forecast that slowly becomes philosophical."
"Write a police blotter entry for a town where nothing truly illegal exists."
"Describe a scientific discovery that sounds mundane but changes everything."
"Write a transcript of a local radio show interrupted by unexpected news."
"Write a travel guide for a place that no longer exists."
"Write a public apology issued by an institution that refuses to admit fault."
"Write an internal email explaining a policy nobody understands."
"Describe a routine day that subtly violates the laws of physics."
"Write a court ruling about a deeply trivial dispute."
"Write a corporate press release announcing something intentionally vague."
"Write a diary entry from someone who does not know they are important."
"Describe a festival whose original purpose has been forgotten."
"Write a meeting summary where the real conflict is omitted."
"Write a technical manual for an object that cannot exist."
"Write a missing persons report that raises more questions than it answers."
"Describe an election decided by an unusual metric."
"Write an FAQ for a product that should not need explanation."
"Write a town history plaque that quietly contradicts itself."
"Write a transcript of a voicemail that was never meant to be heard."
"Describe a research lab shutting down for non-scientific reasons."
"Write a neutral summary of a deeply emotional event."
"Write a performance review for a role that no longer exists."
"Write a safety announcement reacting to an implausible risk."
"Describe a parade observed by someone who dislikes crowds."
"Write a postmortem for a project that technically succeeded."
"Write a zoning dispute that escalates philosophically."
"Write a legal definition of something everyone assumes is obvious."
"Describe a neighborhood rumor that turns out to be accurate."
"Write a museum exhibit description for a recent object."
"Write a transcript of a debate where nobody listens."
"Write an emergency alert that arrives too late."
"Describe a minor innovation that annoys everyone."
"Write a shipping notice for an emotionally significant item."
"Write a company mission statement rewritten five times internally."
"Describe a border that moves slightly every year."
"Write a lab notebook entry expressing quiet doubt."
"Write a community newsletter hiding bad news."
"Write an incident report where nothing is resolved."
"Describe a holiday invented for administrative convenience."
"Write a press interview full of non-answers."
"Write a grant proposal for an oddly specific problem."
"Describe a tradition followed without belief."
"Write a resignation letter that thanks no one."
"Write a town hall speech interrupted by logistics."
"Describe a public space that causes discomfort."
"Write a training manual that assumes competence."
"Write a contract clause that changes everything."
"Describe a protest that remains polite."
"Write a FAQ responding to imaginary complaints."
"Write a maintenance log that reads like fiction."
"Describe a scientific peer review with personal undertones."
"Write a classified summary missing its conclusion."
"Write a weather report that contradicts itself."
"Describe a transportation delay that becomes symbolic."
"Write an HR policy reacting to a unique incident."
"Write a footnote that undermines the main text."
"Describe a community decision reached accidentally."
"Write a security briefing about a non-threat."
"Write a memo correcting a widely believed error."
"Describe an award no one wants to accept."
"Write a procedural checklist with one impossible step."
"Write a town ordinance reacting to a rumor."
"Describe a public apology that feels incomplete."
"Write a research abstract that avoids conclusions."
"Write a timeline with a suspicious gap."
"Describe a ceremony attended out of obligation."
"Write a technical specification with emotional language."
"Write a legal notice that reads like a warning."
"Describe a system functioning exactly as designed, badly."
"Write a user guide for a confusing interface."
"Write a budget summary that reveals priorities indirectly."
"Describe a quiet scandal nobody discusses."
"Write a notification email sent to the wrong group."
"Write a survey where every question is biased."
"Describe a tradition invented last year."
"Write a policy update correcting a loophole."
"Write an official biography missing key facts."
"Describe a routine inspection discovering something abstract."
"Write a post-event report avoiding blame."
"Write a schedule that guarantees conflict."
"Describe a city map that is technically accurate."
"Write an announcement that causes mild panic."
"Write a status update that means nothing."
"Describe an innovation rejected for cultural reasons."
"Write a transcript of a meeting adjourned early."
"Write a closing statement that opens new issues."
)

while [[ true ]];
do
  for prompt in "${prompts[@]}";
  do
    ofc -m ministral-3:3b "$prompt" | tee ./test/`uuidgen`.md
  done
done
