#! /bin/bash

prompts=(
"Write a short piece in any style you choose."
"Describe a scene without naming the location."
"Write a conversation between two people who want different things."
"Tell a story that begins in the middle of an argument."
"Write a description of an object as if it were alive."
"Describe a routine that suddenly changes."
"Write about a decision that feels simple but is not."
"Write a piece that ends with a question."
"Describe a place by listing what is missing from it."
"Write a note that is meant to be read years later."
"Describe a sound that means something important."
"Write a letter that never gets sent."
"Tell a story from the point of view of a bystander."
"Describe a feeling without naming it."
"Write a scene where time seems to slow down."
"Write a memory that might be unreliable."
"Describe a room using only verbs."
"Write a short explanation for a strange rule."
"Describe a journey where the destination keeps changing."
"Write about a promise that is hard to keep."
"Describe a place that is both familiar and new."
"Write about a small mistake with large effects."
"Write a scene where the main conflict is internal."
"Describe a person using their habits only."
"Write a piece that shifts tone halfway through."
"Write a description of a landscape after a change."
"Describe an object that carries a secret."
"Write about an unexpected interruption."
"Tell a story with two endings."
"Write a scene where something is understood without being said."
"Describe a moment of quiet after noise."
"Write about an absence that feels present."
"Describe a day that repeats but never the same way."
"Write a scene where someone waits for news."
"Write about a plan that gets rewritten."
"Describe a place by its textures."
"Write a piece where the narrator changes their mind."
"Describe a meeting where the main topic is avoided."
"Write a short story that takes place over a single minute."
"Describe a ritual that has lost its meaning."
"Write about something that is almost remembered."
"Describe a path that seems to lead nowhere."
"Write a dialogue in which each line is a question."
"Write about a message that arrives too early."
"Describe the difference between two similar things."
"Write a scene that begins with a knock."
"Describe a place using only senses other than sight."
"Write about a choice that feels inevitable."
"Write a piece that includes a list and a confession."
"Describe a moment of recognition."
"Write a story that circles back to its opening image."
"Describe a routine that becomes a performance."
"Write about a misunderstanding that clears something up."
"Write a scene where someone loses and finds something small."
"Describe a setting that is changing faster than the people in it."
"Write about a rule that is followed for the wrong reasons."
"Write a piece with a narrator who is unsure."
"Describe a place as if you are seeing it for the last time."
"Write a scene where the weather mirrors the mood."
"Write about a shortcut that is not shorter."
"Describe a conversation you only hear half of."
"Write a scene that takes place during a power outage."
"Write about an object being returned."
"Describe a moment of hesitation."
"Write a story that includes a map or a diagram."
"Describe a celebration that feels out of place."
"Write about someone trying to be polite and failing."
"Describe a place in terms of light."
"Write a piece where the ending is a beginning."
"Write about an agreement that is never spoken aloud."
"Describe a small act of kindness without naming it."
"Write a scene where two people interpret the same event differently."
"Describe a door and what it separates."
"Write about something that is deliberately left unfinished."
"Write a scene where someone is pretending to listen."
"Describe a decision that is made too late."
"Write about the first time a routine happened."
"Describe a place using only sounds and smells."
"Write a story that ends with a list of options."
"Write about a question that cannot be answered directly."
"Describe a scene where a rule is bent but not broken."
"Write a piece in which the narrator addresses an unknown reader."
"Describe a place where people pass through but do not stay."
"Write a scene where a forgotten item becomes important."
"Write about an apology that is almost accepted."
"Describe an ordinary task made difficult by a small change."
"Write a piece that uses short sentences to build tension."
"Describe a place by what people do there."
"Write about a moment that feels longer than it is."
"Write a scene where someone tells a story within a story."
"Describe a space that feels too large."
"Write about a small victory that no one notices."
"Describe a setting that feels temporary."
"Write a piece where the narrator notices a pattern."
"Write about a coincidence that changes someone’s plan."
"Describe a scene in which someone realizes they are lost."
"Write about a rule that is broken quietly."
"Describe a familiar place after a long absence."
"Write a story that includes a countdown."
"Write about a rumor that might be true."
"Describe a scene where someone avoids a question."
"Write about a pause that matters."
"Describe the feeling of being overheard."
"Write a piece that starts with I remember and ends with I think."
"Write about a small object that becomes a symbol."
"Describe a place where people gather for no clear reason."
"Write about a plan that works but feels wrong."
"Describe a room where something has just happened."
"Write a scene where someone chooses silence."
"Describe a moment that could have gone differently."
"Write about a decision made by coin flip."
"Describe a place using only comparisons."
"Write a story that starts with an apology."
"Write about a conversation interrupted by an announcement."
"Describe a small detail that changes a whole scene."
"Write a piece that takes the form of instructions."
"Write about a task that becomes a ritual."
"Describe a scene where a promise is tested."
"Write about a meeting that ends early."
"Describe a place where time is measured oddly."
"Write about a discovery that raises more questions."
"Describe a scene that is both ordinary and strange."
"Write a piece where the narrator avoids a key detail."
"Write about a note left in a public place."
"Describe a scene where a small object is passed from hand to hand."
"Write about a plan that only exists on paper."
"Describe a moment of relief that comes with doubt."
"Write a story that includes a found message."
"Write about a turn that is taken too soon."
"Describe a place by its shadows."
"Write about a decision made in haste."
"Describe a scene where everyone agrees but for different reasons."
"Write a piece that ends with an image."
"Write about a habit that is hard to break."
"Describe a space that feels crowded even when empty."
"Write about a day that starts late."
"Describe a scene where something is missing and noticed."
"Write a story where the narrator confesses a small truth."
"Write about a promise that is kept quietly."
"Describe a place where rules are implied, not written."
"Write about a moment that feels borrowed."
"Describe a scene where someone waits without knowing for what."
"Write a piece that begins with a list."
"Write about a place that is described only by its edges."
"Describe a conversation where people talk around the topic."
"Write about a decision that leaves no one satisfied."
"Describe a place where a new routine is forming."
"Write a story that ends on a hinge moment."
"Write about a moment when someone chooses to act."
"Describe a setting that feels like it is holding its breath."
"Write a piece that includes a slogan."
"Write about an instruction that is misread."
"Describe a scene where the past intrudes on the present."
"Write about a memory that changes each time it is told."
"Describe a place where everyone seems to know each other."
"Write a piece that relies on understatement."
"Write about a plan that is abandoned and why."
"Describe a scene where someone is late and relieved."
"Write about a question asked at the wrong time."
"Describe a place by its temperature."
"Write a piece in which the narrator notices what others miss."
"Write about a small disagreement that becomes a larger issue."
"Describe a scene that ends before the main event."
"Write about a gesture that is misunderstood."
"Describe a place that is only open briefly."
"Write a piece that includes a schedule."
"Write about a decision made by someone else."
"Describe a scene where the light changes suddenly."
"Write about a promise that feels impossible to keep."
"Describe a place where people come to think."
"Write a story that contains a hidden message."
"Write about a rule that is followed once and then forgotten."
"Describe a scene where someone is seen but not recognized."
"Write about a task that becomes harder as it goes on."
"Describe a moment that feels rehearsed."
"Write a piece where the narrator asks for help."
"Write about a place that is only remembered."
"Describe a scene where two truths collide."
"Write about a change that happens in small steps."
"Describe a setting with a single unusual detail."
"Write a story that begins with a warning."
"Write about a decision that seems obvious in hindsight."
"Describe a scene where someone searches for a word."
"Write a piece that ends with a return to calm."
"Write about a small object that carries a large meaning."
"Describe a place where people are waiting for news."
"Write about a conversation that never finishes."
"Describe a scene where the main character is not the speaker."
"Write a piece that uses a repeating phrase."
"Write about a rule that is quietly rewritten."
"Describe a place where people gather but do not talk."
"Write about a moment of clarity that fades."
"Describe a scene where a routine is interrupted by laughter."
"Write about a plan that hinges on a single detail."
"Describe a place that is defined by its boundaries."
"Write a story that uses a clock as a motif."
"Write about a decision that is reversed."
"Describe a scene where someone leaves without saying goodbye."
"Write a piece that includes an announcement."
"Write about a task that is never finished."
"Describe a place that feels like a threshold."
"Write about a moment when something finally makes sense."
"Describe a scene where someone is asked to explain themselves."
"Write a piece that includes a memory and a plan."
"Write about a change in perspective."
"Describe a scene where a small signal is ignored."
"Write a story that begins with a mistake."
"Write about a promise made in passing."
"Describe a place where people come and go in waves."
"Write about a decision that is postponed."
"Describe a scene where something is nearly said."
"Write a piece that ends with a description of the sky."
"Write about a person who collects small details."
"Describe a place where the rules are unclear."
"Write about a short trip that changes someone."
"Describe a scene where someone revises their story."
"Write a piece that includes a reminder."
"Write about a choice that feels like a test."
"Describe a place that is half-finished."
"Write about a moment of indecision."
"Describe a scene where the background becomes important."
"Write a story that uses parallel scenes."
"Write about a promise that is misunderstood."
"Describe a place that feels like it is listening."
"Write about a simple act that becomes significant."
"Describe a scene where the future is discussed vaguely."
"Write a piece that ends with someone walking away."
"Write about a misunderstanding that reveals the truth."
"Describe a place where people leave notes for each other."
"Write about a decision made with incomplete information."
"Describe a scene where silence is the response."
"Write a piece that includes a list of rules."
"Write about a question that echoes."
"Describe a place where time feels off."
"Write about a day that feels too short."
"Describe a scene where someone changes the subject."
"Write a story that begins with You shouldn't be here."
"Write about a moment when someone chooses to wait."
"Describe a place by what it refuses to show."
"Write about a habit that becomes a problem."
"Describe a scene where two people understand each other suddenly."
"Write a piece that includes a brief announcement."
"Write about a decision that is made for someone else."
"Describe a place where people whisper."
"Write about a conversation that is only remembered later."
"Describe a scene where the rules change midstream."
"Write a piece that ends with an unanswered question."
"Write about a moment of regret that is quickly hidden."
"Describe a place where nothing is permanent."
"Write about a small change that goes unnoticed."
"Describe a scene where someone is unsure what they saw."
"Write a piece that includes a simple instruction and a warning."
"Write about a decision that splits a group."
"Describe a place that feels like a pause."
"Write about a meeting that accomplishes something unexpected."
"Describe a scene where someone is caught off guard."
"Write a piece that includes a reminder and a request."
"Write about a moment when a plan becomes a story."
"Describe a place where light behaves strangely."
"Write about a scene where someone chooses the longer path."
"Describe a place where the past is visible."
"Write a piece that begins with an observation."
"Write about a decision that feels like a leap."
"Describe a scene where something ends quietly."
"Write about a moment that cannot be repeated."
"Describe a place where people avoid eye contact."
"Write a piece that uses the word however three times."
"Write about a plan that depends on a small kindness."
"Describe a scene where someone is asked to wait."
"Write about a place that feels temporary but is not."
"Describe a scene where someone realizes a pattern."
"Write a piece that ends with a small detail."
"Write about a decision made under a deadline."
"Describe a place where the rules are new."
"Write about a moment when someone changes their mind."
"Describe a scene where a promise is remembered."
"Write a piece that begins with It wasn't supposed to happen like this."
"Write about a small discovery that shifts everything."
"Describe a place where people speak softly."
"Write about a decision that feels like a compromise."
"Describe a scene where the surroundings are more important than the action."
"Write a piece that includes a line of dialogue that repeats."
"Write about a moment when someone feels out of place."
"Describe a place where people come to listen."
"Write about a scene where a plan is set aside."
"Describe a place that feels like the edge of something."
"Write a piece that ends with an admission."
"Write about a decision that is made in silence."
"Describe a scene where a small object changes hands."
"Write about a moment when someone chooses to tell the truth."
"Describe a place where people are passing through."
"Write a piece that begins with We didn't mean for this to happen."
"Write about a change that comes from a small action."
"Describe a scene where something is promised."
"Write about a place that feels unfinished."
"Describe a scene where someone is searching for something intangible."
"Write a piece that ends with someone arriving."
"Write about a decision that is made without words."
"Describe a place where a new routine is forming."
"Write about a moment when someone notices a small detail."
)

while [[ true ]];
do
  for prompt in "${prompts[@]}";
  do
    ofc -m ministral-3:3b "$prompt" | tee ./train/`uuidgen`.md
  done
done
