use std::path::PathBuf;

use burn::module::Module;
use burn::prelude::Device;
use burn::store::ModuleRecord;
use clap::Parser;
use lm_core::generation::generate_tokens;
use lm_core::model::ModelConfig;

/// Train a language model or generate text from an existing model.
#[derive(Parser, Debug)]
enum Command {
    /// Generate text using saved model weights.
    Generate {
        /// The total number of transformer blocks.
        transformer_blocks: usize,
        embed_dims: usize,
        /// The number of attention heads to use in the transformer.
        attn_heads: usize,
        /// The size of the perceptrons between the attention blocks.
        percept_size: usize,
        /// Controls randomness when sampling tokens.
        #[arg(long, default_value_t = 0.3)]
        temperature: f64,
        /// Cumulative probability threshold used for nucleus sampling.
        #[arg(long, default_value_t = 0.6)]
        top_p: f64,
        /// Penalty applied to tokens that already appear in the context.
        #[arg(long, default_value_t = 1.2)]
        repetition_penalty: f64,
        /// Maximum number of generated bytes, excluding the prompt.
        #[arg(long)]
        max_generated_bytes: Option<usize>,
        load_from: PathBuf,
        context: String,
    },
    /// Train a language model from file-based or Dolma datasets.
    Train {
        train_data: PathBuf,
        test_data: PathBuf,
        dropout: f64,
        /// Base learning-rate factor for the Noam scheduler.
        #[clap(default_value_t = 0.1, required = true)]
        lr_factor: f64,
        /// The total number of transformer blocks.
        transformer_blocks: usize,
        embed_dims: usize,
        /// The number of attention heads to use in the transformer.
        attn_heads: usize,
        /// The size of the perceptrons between the attention blocks.
        percept_size: usize,
        epochs: usize,
        #[arg(short, long)]
        start_model: Option<PathBuf>,
        #[arg(long)]
        start_optimizer: Option<PathBuf>,
        save_to: PathBuf,
    },
}

fn main() {
    let command = Command::parse();

    match command {
        Command::Train {
            train_data,
            test_data,
            dropout,
            lr_factor,
            transformer_blocks,
            embed_dims,
            attn_heads,
            percept_size,
            epochs,
            start_model,
            start_optimizer,
            save_to,
        } => {
            let record = start_model.map(|path| {
                ModuleRecord::load(path)
                    .expect("Should be able to load the model weights from the provided file")
            });

            let model = lm_core::training::train(
                Device::wgpu(Default::default()),
                ModelConfig::new(transformer_blocks, embed_dims, attn_heads, percept_size)
                    .with_dropout(dropout),
                train_data,
                test_data,
                epochs,
                lr_factor,
                record,
                start_optimizer,
            );

            model.save_file(save_to).unwrap();
        }

        Command::Generate {
            load_from,
            context,
            transformer_blocks,
            embed_dims,
            attn_heads,
            temperature,
            top_p,
            repetition_penalty,
            max_generated_bytes,
            percept_size,
        } => {
            #[allow(deprecated)]
            let device = Device::ndarray();

            let record = ModuleRecord::load(load_from)
                .expect("Should be able to load the model weights from the provided file");

            let mut model =
                ModelConfig::new(transformer_blocks, embed_dims, attn_heads, percept_size)
                    .init(&device);
            model = model.load_record(record);

            let ctx_chars: Vec<_> = context.chars().collect();

            generate_tokens(
                &model,
                &ctx_chars,
                temperature,
                repetition_penalty,
                top_p,
                max_generated_bytes,
            );
        }
    }
}
